### ISSUE TITLE
`--test-categories` option doesn't work

### ISSUE THREAD

**Issue by jwasinger** [ethereum/execution-spec-tests#120]
Executing the example: ` tf --output="fixtures" --test-categories vm/vm_arith/vm_add` yields:
```
INFO:ethereum_test_filling_tool.filler:collected 0 fillers
```

**Comment by spencer-tb** [comment]
Apologies, the readme/documentation uses the incorrect format. I believe you have already figured it out from you PR by using `.` between directories instead of `/`.
