### ISSUE TITLE
Unclear meaning 'protected' field exported in transactions

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#168]
Error: BlockchainTestInFilled convertion error: BlockchainTestBlock convertion error: LegacyTransaction convertion error: Unexpected field 'protected' in config: TransactionLegacy 

A python specific field is exported to generated tests transaction section:

```
"protected" : false,
```

**Comment by spencer-tb** [comment]
Re - Mario's comment on what the protected field is used for: 
> It's referring to the two different types of transactions described in [EIP-155](https://eips.ethereum.org/EIPS/eip-155), and instructs the client on how they should sign the transaction.
> 
> If set to false, the transaction should be signed without taking into account any Chain ID info.
> 
> If set to true, the transaction should be signed using the method described in the EIP.

**Comment by winsvega** [comment]
I think it is unclear what this field means. better to print vrs explicitly.

**Comment by winsvega** [comment]
So we agree that when exporting transaction in the test, just setting v field is enough ( the rest is defined in rlp) 
since if someone would want to sign a tx themselvs they will get different rs values anyway it does not make much sense to export rs. but looking at v encoding they can still deduct chainid or determain tx type on old networks

**Comment by marioevz** [comment]
Fixed by #187
