### ISSUE TITLE
solc error messages

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#189]
if yul or solidity code failed to compile the error messaging should be follow:

1) message if solc not detected when filling a solc require test filler
2) message that the test required a different solc version to the one that found
3) message the exact code that failed to compile with found solc version

I suggest to maintain all tests to use the latest version of solc to avoid solc versioning managment.

**Comment by danceratopz** [comment]
- The last few versions of solc are supported (currently 0.8.20, 0.8.21, and custom builds of upcoming 0.8.22). 
- Test cases do not specify which version of solc is required to compile the yul defined within the test.

The following error messages are provided:
1. `solc` not found
    ```
    fill tests/homestead/yul/test_yul_example.py -x --solc-bin=/home/dtopz/bin/solc-0.123.0
    ```
    says:
    ```
    INTERNALERROR> Exception: `solc` binary executable not found, please refer to
    INTERNALERROR>                 https://docs.soliditylang.org/en/latest/installing-solidity.html
    INTERNALERROR>                 for help downloading and installing `solc`
    ```
2. Not applicable as it currently stands.
3. Example error:
    ```
    <----snip---->
                if result.returncode != 0:
                    stderr_lines = result.stderr.decode().split("\n")
                    stderr_message = "\n".join(line.strip() for line in stderr_lines)
    >               raise Exception(f"failed to compile yul source:\n{stderr_message[7:]}")
    E               Exception: failed to compile yul source:
    E               Function "retrn" not found.
    E               --> <stdin>:8:17:
    E               |
    E               8 |                 retrn(0, 32)
    E               |                 ^^^^^
  
    

    src/ethereum_test_tools/code/yul.py:99: Exception
    ============= short test summary info ============
    FAILED tests/homestead/yul/test_yul_example.py::test_yul[fork=Homestead] - Exception: failed to compile yul source:
    ```
