### ISSUE TITLE
pyspec fails to detect supported forks

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#190]
```
fill -v ./tests/test_acl.py --output ./tests/out  --evm-bin /home/wins/.retesteth/nimbus/start.sh --flat-output
Error: The configured evm tool doesn't support the following forks: Frontier, Homestead, Byzantium, Constantinople, ConstantinopleFix, Istanbul, Berlin, London, Merge, Shanghai.
```
Please specify a version of the evm tool which supports these forks or use --until FORK to specify a supported fork.

Exit: Incompatible evm tool with fork range.

this message is incorrect. nimbus support all of those forks

**UP:**
found the issue. nimbus evm does not have t8n arg. 
so it is not evm `t8n` --help it is plain `evm --help`

also some clients evms have `-v`  and others `--version` for version info

**Comment by danceratopz** [comment]
Example: When filling with solc 0.8.17 using 09716f00906cfd0effa88313011d5497d8315897: http://pastie.org/p/4cV1OEIpCnbxsIvAjKSg9n.
solc 0.8.20 fills correctly.
