### ISSUE TITLE
feat(fill): better json debug print upon test fail

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#197]
when error happens env,pre,alloc files are printed as json but in one line. better to print it as pretty json for readability from console log

this is how it is printed right now:
```
self = <evm_transition_tool.EvmTransitionTool object at 0x7fcceccd8fd0>
alloc = {'0x0000000000000000000000000000000000000100': {'balance': '0x00', 'code': '0x6000496000556001496001556002496002556003...e': '0x600049600055600149600155600249600255600349600355600449600455600549600555', 'nonce': '0x00', 'storage': {}}, ...}
txs = []
env = {'currentBaseFee': '7', 'currentCoinbase': '0x0000000000000000000000000000000000000000', 'currentDifficulty': '0x0', 'currentGasLimit': '0x0', ...}
fork = Cancun, chain_id = 1, reward = -1, eips = None
```

it is even shortened so I try to investigate env contents and I don't see which fields are provided

**Comment by danceratopz** [comment]
I think this is standard pytest output that just includes the local variables in the context of a test failure. Is that right? 

If so, I will have a look to see if we can modify this standard behavior.

However, you can drop into a debugger directly in the terminal upon a test fail by specifying `--pdb -nauto` and inspect these elements. 

To get a nice print in the console you can execute:

```python
(Pdb) import json
(Pdb) print(json.dumps(alloc, indent=2))
```

If the object is not already a json string, you can use `to_json`. For example:

```python
(Pdb) import json
(Pdb) from ethereum_test_tools.common import to_json
(Pdb) print(json.dumps(to_json(txs[0]), indent=2))
```

will print:

```console
{
  "type": "0x0",
  "chainId": "0x1",
  "nonce": "0x0",
  "gasPrice": "0xa",
  "gas": "0x7a120",
  "value": "0x0",
  "input": "0x",
  "to": "0x0000000000000000000000000000000000000100",
  "sender": "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b",
  "v": "0x1c",
  "r": "0xf73b923883495dc2174285c8fa4176de3d45accfb11cc8034ea1dd09831a4ddf",
  "s": "0x1c6bccbcd655b4022bcc27de4b9d5cee9ce999cdb8459b0afec4f5054ea02243"
}
```

**Comment by danceratopz** [comment]
We can't display all variables within the current scope upon fail, but we can try and improve error reporting, closing in favor of #320.
