### ISSUE TITLE
Redundant info field engineNewPayload

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#202]
the information you put in this field is already printed in all the json sections:
(blockheader, transactions, uncleheaders, withdrawals) 

https://github.com/ethereum/tests/blob/develop/EIPTests/BlockchainTests/bcEIP4844-blobtransactions/blockWithAllTransactionTypes.json#L89

**Comment by winsvega** [comment]
I don't understand why you need to dublicate fields in test. You can take tx rlp from block rlp, and blobhashes from transaction section. And blockheader from header

Its like you create another test format within inside blockchain test. Then it's better to make a new format

Because you basically take blockchain test format and pack it inside the payload field in slightly different structure. Then the content of payload field can be a new type of test

**Comment by marioevz** [comment]
This field is helpful because there are some tests that use a different format to serialize the RLP than it would be expected by hive. E.g. see https://github.com/ethereum/execution-spec-tests/blob/main/tests/cancun/eip4844_blobs/test_blob_txs_full.py

We can skip a lot of code in hive if the tests this repo generate all the necessary information it already has.

#210 adds a flag to remove this information if necessary.

**Comment by winsvega** [comment]
> This field is helpful because there are some tests that use a different format to serialize the RLP than it would be expected by hive. E.g. see https://github.com/ethereum/execution-spec-tests/blob/main/tests/cancun/eip4844_blobs/test_blob_txs_full.py
> 
> We can skip a lot of code in hive if the tests this repo generate all the necessary information it already has.
> 
> #210 adds a flag to remove this information if necessary.

Maybe I am missing smth.
Because what I see in this field is the json information collected from other test fields. (Blockheader, transaction,)
Let me double check

**Comment by winsvega** [comment]
I don't see any new fields introduced in this engine payload field. 
So you just repack existing fields into engine payload?

**Comment by winsvega** [comment]
Maybe it is better to make a new test suite?

**Comment by danceratopz** [comment]
- #210 added `--disable-hive`. When this flag is specified, these fields won't be written to the fixtures.
- #301 replaced `--disable-hive` with `--enable-hive; be default these fields are written to fixtures.

So since #301, these fields should no longer be visible in fixtures by default.
