### ISSUE TITLE
make a custom t8n (mostlikely pyt8n) to generate invalid states

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#209]
How do you like the idea of a super t8n tool (potentially pyt8n) that can construct states with ethereum rules violated (bigint balances, withdrawals, gaslimit, formulas violated)

I think it is too much to ask from dev teams to support it so I am thinking about pyt8n as a candidate for this role. 

https://github.com/ethereum/tests/issues/1244

**Comment by danceratopz** [comment]
@spencer-tb Perhaps a complimentary approach to #242?

**Comment by spencer-tb** [comment]
Closing in favor of #242 and the WIP PR https://github.com/ethereum/execution-spec-tests/pull/272
