### ISSUE TITLE
Don't install git submodule for execution specs dependency

### ISSUE THREAD

**Issue by lightclient** [ethereum/execution-spec-tests#22]
Right now `tox` takes a very long time due to `ethereum/tests` submodule in the execution specs. Would be great to avoid that if possible.

```console
py3: 290 W install_package_deps> python -I -m pip install 'black==22.3.0; implementation_name == "cpython"' 'ethereum@ git+https://github.com/ethereum/execution-specs.git' 'flake8-docstrings<2,>=1.6' 'flake8-spellcheck<0.25,>=0.24' 'flake8<4,>=3.9' 'isort<6,>=5.8' 'mypy==0.982; implementation_name == "cpython"' 'pytest-cov<3,>=2.12' 'pytest-xdist<3,>=2.3.0' 'pytest>=7.2' setuptools==58.3.0 types-setuptools==57.4.4 [tox/tox_env/api.py:421]
Collecting ethereum@ git+https://github.com/ethereum/execution-specs.git
  Cloning https://github.com/ethereum/execution-specs.git to /private/var/folders/ty/5cq1d6311cb7ggy9b6l092mc0000gp/T/pip-install-fs175whv/ethereum_5c59a4a099f64df29efcfb5502fcb23a
  Running command git clone --filter=blob:none --quiet https://github.com/ethereum/execution-specs.git /private/var/folders/ty/5cq1d6311cb7ggy9b6l092mc0000gp/T/pip-install-fs175whv/ethereum_5c59a4a099f64df29efcfb5502fcb23a
  Resolved https://github.com/ethereum/execution-specs.git to commit 95ef6bf957a4c66993168384cec395ef1a030026
  Running command git submodule update --init --recursive -q
```

**Comment by danceratopz** [comment]
Looks like execution-specs is only required for rlp encoding and keccak hash calculation in the `compute_create_address` and `compute_create2_address` helper functions. This can be avoided if it's ok to use the implementations from the ethereum/pyrlp and ethereum/eth-hash instead, see #24.

**Comment by lightclient** [comment]
Hi, as I mentioned in #24, I would much prefer to rely on the `execution-specs` repository as much as possible.

**Comment by danceratopz** [comment]
Thanks again for the explanation. I closed #24 where I commented that it doesn't appear to be possible to stop setuptools/pip installing the ethereum/tests submodule dependency when installing execution-specs as a git dependency.

**Comment by spencer-tb** [comment]
I've had a play around with this today as when running tox (during the git submodule for `tests/fixtures`) my laptop would either crash or I'd get an error saying I didn't have enough disk space :disappointed:

As a workaround I've forked the `ethereum/execution-specs` repo, and created a branch without the `tests/fixtures` submodule. Then pointed the `install_requires` in _setup.cfg_ to that [branch](https://github.com/spencer-tb/execution-specs/tree/exec-spec-tests-tox).

Its not the ideal solution but I can create a PR for this if its useful. I'm going to add a ` .git/workflow` to the forked git branch such that its kept up-to-date with upstream whilst ignoring the `tests/fixtures` submodules.

**Comment by gurukamath** [comment]
Post [#708](https://github.com/ethereum/execution-specs/pull/708) the `execution-specs` no longer fetch the fixtures by default. Hope this solves the issue here.

**Comment by spencer-tb** [comment]
Great thanks! Tox is now much **much** faster for me and my laptop doesn't crash now :smiley: 

Closing this issue.
