### ISSUE TITLE
:bricks: Feature: Add the go-ethereum `evm blocktest` within tox

### ISSUE THREAD

**Issue by spencer-tb** [ethereum/execution-spec-tests#237]
## Feature Description

We have the occasional case where we may generate an invalid test fixture. Currently test fixtures can be checked for validity using the:
```
evm blocktest <path_to_fixture.json>
```
command from go-ethereum's evm.

To check the validity of all tests after generation, we could add an additional step during tox, that runs the above command on every generated fixture.

**Comment by danceratopz** [comment]
This will actually execute all the tests against geth, which might be overkill for our usual `test.yaml` workflow.

We could perhaps:
1. Add a new tox environment that doesn't get ran by default, like `testenv:tests-develop` added in #302.
2. Execute this test environment in a dedicated ci workflow. I'm not sure what this would look like, something executes daily on main and all branches from open PRs could be nice?

**Comment by spencer-tb** [comment]
This sounds like a great option 💯
