### ISSUE TITLE
Add Engine API ForkchoiceUpdated version to the fixture

### ISSUE THREAD

**Issue by marioevz** [ethereum/execution-spec-tests#255]
Add Engine API ForkchoiceUpdated version to the fixture so hive can read this and send the appropriate directive to the client.

**Comment by danceratopz** [comment]
@spencer-tb: Does https://github.com/ethereum/execution-spec-tests/commit/1050c028d0a8537a1f6d85bf005807a3f4cc1eaa fix this?
