### ISSUE TITLE
exception name consistency

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#259]
I see 2 different exception strings but the meaning is the same

```
"invalid excess blob gas" : "Error in field: excessBlobGas",
      "invalid excessBlobGas" : "Error in field: excessBlobGas",
```

**Comment by spencer-tb** [comment]
Nice - should be changed here:

https://github.com/ethereum/execution-spec-tests/blob/main/tests/cancun/eip4844_blobs/test_excess_blob_gas.py#L518

**Comment by winsvega** [comment]
also the names are too general like this one:
`invalid transaction`  referes actually to an invalid blob transaction. and within inside the transaction could be much more exceptions. I suggest using exception codes like INVALID_TR_1  that will refer to particular exception  string

**Comment by winsvega** [comment]
also here you put an expected exception, but the returned exception is actually different

```
Error: insufficient_account_balance Not found in client response to postmine block tweak!
Import result of postmine block: 
'Error importing raw rlp block: max priority fee per gas higher than max fee per gas: address 0xa94f5374Fce5edBC8E2a8697C15331677e6EbF0B, maxPriorityFeePerGas: 8, maxFeePerGas: 7',
 Test Expected: 
'insufficient funds for gas * price'
 (cancun/eip4844_blobs/001-fork=Cancun--exact_balance_minus_1-tx_max_fee_per_blob_gas=1-no_calldata-tx_value=0-tx_max_priority_fee_per_gas=8, fork: Cancun, block: 1)
```

**Comment by winsvega** [comment]
```
Error: Invalid params Not found in client response to postmine block tweak!
Import result of postmine block: 
'Error importing raw rlp block: blob transaction with zero blobs',
 Test Expected: 
'unknown block type'
 (cancun/eip4844_blobs/000-fork=ShanghaiToCancunAtTime15k-no_blob_tx, fork: ShanghaiToCancunAtTime15k, block: 1)
```

Can be that `Invalid params` in the produced test stands for multiple different exceptions. such as invalid block encoding and tx with 0 blobs.

**Comment by winsvega** [comment]
fixed now with the PR
