### ISSUE TITLE
Release v0.1.0 chain format is wrong

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#27]
Issue 1: 
- test format missing `genesisRLP` field

Issue 2:
- genesis block has difficulty != 0, but also has withdrawalsRoot defined which makes it Merge. Merge block has difficulty = 0.

**Comment by lightclient** [comment]
> test format missing `genesisRLP` field

Is this field used anywhere? AFAIK, all clients initialize the genesis block using the genesis config and them import all blocks after genesis via `import`-like subcommand. This is how hive works across all clients.

> genesis block has difficulty != 0, but also has withdrawalsRoot defined which makes it Merge. Merge block has difficulty = 0.

Not sure if this is true. In the `env` argument to `t8n`, yes, difficulty must equal 0 when post-merge and a prevRandom value must be provided. However, the genesis header in the filled test is a normal block header encoded in json, which currently [does not support](https://github.com/ethereum/execution-apis/blob/939255f467f9c5700a65426159afdfc0e0a66060/src/schemas/block.yaml#L1) prevRandom.
