### ISSUE TITLE
Cancun failures

### ISSUE THREAD

**Issue by holiman** [ethereum/execution-spec-tests#332]
I'm tryng to get the most recent tests to work with geth, and have a PR opened there:https://github.com/ethereum/go-ethereum/pull/28337

Currently investigating the very first test in `/cancun/eip5656_mcopy/mcopy_memory_expansion/mcopy_huge_memory_expansion.json`,  called `000-fork=Cancun-from_existent_memory-successful=False--max_dest_single_byte_expansion`. 

```
[user@work go-ethereum]$ go run   ./cmd/evm/ --json  blocktest ./tests/spec-tests/fixtures/cancun/eip5656_mcopy/mcopy_memory_expansion/mcopy_huge_memory_expansion.json
...
{"pc":47,"op":94,"gas":"0x5dd9e6e","gasCost":"0x3","memSize":256,"stack":["0x0","0x0","0x1","0x0","0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"],"depth":2,"refund":0,"opName":"MCOPY","error":"gas uint64 overflow"}
{"pc":38,"op":85,"gas":"0x17d5d2","gasCost":"0x5654","memSize":256,"stack":["0x1","0x0"],"depth":1,"refund":0,"opName":"SSTORE"}
{"pc":39,"op":0,"gas":"0x177f7e","gasCost":"0x0","memSize":256,"stack":[],"depth":1,"refund":0,"opName":"STOP"}
...
########## BAD BLOCK #########
Block: 1 (0x0133b010e20067d6f0c1fac34c8245b8968d87d968ca3096ef8eeeb14d7e92c0)
Error: invalid merkle root (remote: 27557b93e5bb671d712b61c0da570f6883abbc7bd2da95f0af4e462f139f41bb local: 1051394ef6cb6fbcc2838024c0ca9ff6ca975ef4aefc041d82608ce36f44e7c7) dberr: %!w(<nil>)

```

~~This is the (complete) state that I get~~ EDIT: not accurate
```json
{
    "root": "1051394ef6cb6fbcc2838024c0ca9ff6ca975ef4aefc041d82608ce36f44e7c7",
    "accounts": {
        "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b": {
            "balance": "10779762",
            "nonce": 1,
            "root": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
            "codeHash": "0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470"
        }
    }
}
```

Curious to know what the expected state is...?

**Comment by danceratopz** [comment]
Hi @holiman, please see https://github.com/ethereum/go-ethereum/pull/28337#pullrequestreview-1679804684.

Regarding the problem in this ticket, I just built https://github.com/ethereum/go-ethereum/tree/509a64ffb9405942396276ae111d06f9bded9221 and used the `fixtures_develop.tar.gz` from [release v1.0.5](https://github.com/ethereum/execution-spec-tests/releases/tag/v1.0.5). Running the following works locally for me:

```console
/home/dtopz/code/github/ethereum/go-ethereum/build/bin/evm --version
# -> evm version 1.13.4-unstable-509a64ff-20231013
/home/dtopz/code/github/ethereum/go-ethereum/build/bin/evm blocktest ./fixtures_dev/cancun/eip5656_mcopy/mcopy_memory_expansion/mcopy_huge_memory_expansion.json
```

Which geth branch are you using? Respectively which version of the fixtures are you using?

**Comment by holiman** [comment]
Thanks for the help, it's sorted now!
