### ISSUE TITLE
Update framework tests and docs for solc 0.8.23

### ISSUE THREAD

**Issue by danceratopz** [ethereum/execution-spec-tests#345]
https://github.com/ethereum/solidity/releases/tag/v0.8.23

**Comment by richardgreg** [comment]
@danceratopz could simplify what needs to be done here?

**Comment by danceratopz** [comment]
@richardgreg 0.8.23 is predominantly a bugfix release, so it shouldn't break any tests. In that case, it should be a relatively straight-forward version bump - take have a look at #340 which updated for solc 0.8.22.

If you like, you could also try seeing if we can make use of the following feature listed in the [0.8.23 release notes](https://github.com/ethereum/solidity/releases/tag/v0.8.23) in the default command-line args we provide to solc:

> Commandline Interface: An empty --yul-optimizations sequence can now be always provided.

Disabling optimizations is good for testing as the resulting bytecode should be generated more deterministically.
