### ISSUE TITLE
RLP of Shanghai blocks should always have withdrawals list

### ISSUE THREAD

**Issue by yperbasis** [ethereum/execution-spec-tests#36]
Even when they don't contain withdrawals, RLP of such blocks should contain an empty list for withdrawals post-Shanghai. For example, block 2 in `withdrawals_use_value_in_contract.json` in Release [v0.2.1](https://github.com/ethereum/execution-spec-tests/releases/tag/v0.2.1) fixtures has RLP 
```0xf90282f9021aa08444423fbde249cfcd3c41bdf009368a8b77763ed9fe344db4a32b0ecdc8d7b3a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347942adc25665018aa1fe0e6bc666dac8fc2697ff9baa06ab526318fc1842c06d5440bf245b03112e15241ea5d1f9f013ff6cf81296376a08c500edaa09a8dce41c0dcce8ee2876f5f3150b8101d09faa9ba61db523507eaa0cda4364d9e43f15119746d96fb9d842997acbfa55f65b6d3f7a3b5f06cd250d1b9010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800288016345785d8a000083012e731880a0000000000000000000000000000000000000000000000000000000000000000088000000000000000007a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421f862f860010a830186a0940000000000000000000000000000000000000100808026a025b1502ca1862804cfb6dca49ffb3cca3d8225a66df185ca857aab6f8a1f97a3a05d9178ca2d7a23b22e07ff2fe9a01ceb23a4acf041a0fcdf3d31752de802b74ec0```
but it should end with `c0c0` (one empty list for uncles and one empty list for withdrawals).

Also blocks in `initcode_limit_contract_creating_tx_gas_usage.json` suffer from this issue.

**Comment by spencer-tb** [comment]
https://github.com/ethereum/execution-spec-tests/pull/37 is a WIP but should resolve the issue. Thanks for the find :happy:

**Comment by gurukamath** [comment]
The withdrawals are missing in the rip for the second block of the `withdrawals_balance_within_block.json` test as well

**Comment by spencer-tb** [comment]
The PR merged above should resolve these issues. Please re-open if anything similar persists.
