### ISSUE TITLE
Exported test format not following the existing tests schema: Value format

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#39]
Pyscpecs export 

```
"nonce": "0x0",
```

its a t8n tool format. we have different schema in tests, requested long time ago by teams
 
```
"0x00" for 0  "0x" for empty code
"0x01"  for 1.  so the data always padded to 1 byte
```

there was a discussion long time ago. I don't know if it is relevant to the testing team who initially asked about it. but we stick to this format

```
"balance": "0x432ae"    ->                   "balance": "0x0432ae"
```

but in storage we save the space 

```
                    "0x0000000000000000000000000000000000000000000000000000000000000001": "0x000000000000000000000000000000000000000000000000000000003b9aca00",
                    "0x0000000000000000000000000000000000000000000000000000000000000002": "0x0000000000000000000000000000000000000000000000000000000077359400"
```

would be 
```
                    "0x01": "0x3b9aca00",
                    "0x02": "0x77359400"
```

**Comment by spencer-tb** [comment]
Here is an example of the updated format for the accounts:

![image](https://user-images.githubusercontent.com/60348173/214648983-8d9e5ace-a02f-4f24-a850-916ac2d836bf.png)



Compared to the old format:

![image](https://user-images.githubusercontent.com/60348173/214648893-315c0e4b-3cd2-465a-b407-04a75f3f09b8.png)


Is the fixture formatting in these issues only relevant to the pre and postState accounts?

**Comment by winsvega** [comment]
if we speak about accounts yes. but the format remains the same for all fields.

 such as in transaction: value,data,gasPrice and so on.
 in Blockheaders. btw. nonce and mixhash has fixed length. as well as other hashes. in GenesisHeader. 

the only exception I see is                 `"blocknumber" : "2",` because that one is a debug field for human to read it is in dec format. also optional.

**Comment by spencer-tb** [comment]
Closing after merging: #47
