### ISSUE TITLE
Make use of features from solc 0.8.23 release

### ISSUE THREAD

**Issue by richardgreg** [ethereum/execution-spec-tests#395]
Most specifically the following feature
> Commandline Interface: An empty --yul-optimizations sequence can now be always provided.

Ref: #345

**Comment by richardgreg** [comment]
Hi @danceratopz, I've gone through the docs and have a fair understanding of the program, though my lack of blockchain background holds me back a bit. 

If I'm not wrong, the files in `ethereum_test_tools` help with test execution by customising pytest, right? Could you give me an example of such a command, using the `solc` command line?

**Comment by danceratopz** [comment]
Hey @richardgreg :+1: 

The pytest-specific config/customization is in `src/pytest_plugins/`. The libraries in `src/ethereum_test_tools/` help generate test vectors/fixtures (that are subsequently used by ethereum execution clients) but try to be independent of pytest (i.e., you could use a different test framework/runner but still use these libraries to generate test fixtures). 

`ethereum_test_tools` does many things such as defining all the different types required to define test fixtures (accounts, blocks, transactions, etc), define the "test fixture" specifications and help write these resulting fixtures to JSON files. 

As you might have seen, the `Yul` class from `ethereum_test_tools` helps compile any Yul source constained in tests, here are the relevant lines.
https://github.com/ethereum/execution-spec-tests/blob/ccf25a322bf37a1c0fd9d6498c5e9edfaeb0d098/src/ethereum_test_tools/code/yul.py#L83-L97

If you'd like to see how the framework is calling `solc`, you can set some breakpoints or add some print statements here, for exampe:
```
print('\necho "' + self.source + '" | ' + " ".join(str(arg) for arg in solc_args))
```
which results in:
```
echo "
              {
                  function f(a, b) -> c {
                      c := add(a, b)
                  }

                  sstore(0, f(1, 2))
                  return(0, 32)
              }
              " | solc --evm-version shanghai --assemble -
```

(running `fill tests/homestead/yul/test_yul_example.py --fork=Shanghai -s -v`).

**Comment by danceratopz** [comment]
See https://github.com/ethereum/execution-spec-tests/pull/467#issuecomment-1999531425.
