### ISSUE TITLE
generated folder name is state_tests but cmd is -m state_test

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#396]
adds a confusion.

**Comment by danceratopz** [comment]
I think this is ok and can't shouldn't be changed.

You can pass `-m state_test` to `fill`: This is a pytest flag that filters tests that have been marked as a `state_test`, in the case of the `state_test` marker, this is done automatically, but in general this is done via a decorator on the test itself. For example,
```python
@pytest.mark.state_test
def test_foo(state_test):
    pass
```
So `state_test` is the right name for the mark, imo, whereas the directory contains many state tests.

`m state_test`  = "filter by `state_test`"

**Comment by winsvega** [comment]
just a suggestion.
