### ISSUE TITLE
Invalid fork name `ShanghaiToCancunAtTime15k` in `state_tests`.

### ISSUE THREAD

**Issue by chfast** [ethereum/execution-spec-tests#405]
The `ShanghaiToCancunAtTime15k` is invalid fork name in a `StateTest` because they execute single transaction/block. You need to pick `Shanghai` or `Cancun` during test generation.

**Comment by marioevz** [comment]
Upon taking a look of the tests that do this:
- `test_blob_type_tx_pre_fork`
- `test_point_evaluation_precompile_before_fork`
- `test_blobbasefee_before_fork`

The idea behind these tests was that, on the blockchain-test version, the fork configuration contains the scheduled upcoming fork.

So it might be worth it to do the fix as you suggested on discord, where we pass the fork that is enabled according to the block timestamp and number to the state test, while we use the transition fork for the blockchain test version.
