### ISSUE TITLE
BlockchainTests should only have one failing block at most

### ISSUE THREAD

**Issue by marioevz** [ethereum/execution-spec-tests#41]
The tests should be more restrictive in a way that every yielded test should contain:
- At most 1 invalid block
- It should always be the last block

For example, on test: https://github.com/ethereum/execution-spec-tests/blob/4de323c5b5e741488dd2b47efde5f63f7cc7f09c/fillers/withdrawals/withdrawals.py#L63-L108
We produce three blocks where the first block is invalid, and then two invalid blocks, but this test could stick to these restrictions by yielding two times: once with only the invalid block, and afterwards with the two valid blocks.

Also, ideally, the filler should catch and restrict this behavior and throw an error when we try to fill a test that does not follow this convention.

**Comment by winsvega** [comment]
why one block only?
