### ISSUE TITLE
type3 tx rejected on Cancun looks valid (INSUFFICIENT_MAX_FEE_PER_BLOB_GAS)

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#412]
hmm. should this tx be rejected on Cancun? 

Test Expected: TransactionException.INSUFFICIENT_MAX_FEE_PER_BLOB_GAS (cancun/eip4844_blobs/tests/tmp/tmptest_25dd1421_6775_49e2_ad55_0e77287c7395/test_blob_txs.py::test_invalid_tx_max_fee_per_blob_gas_state[fork_Cancun-state_test-insufficient_max_fee_per_blob_gas], fork: Cancun, TrInfo: d: 0, g: 0, v: 0, TrData: ` 0x..`)

why? 

```
{
    "data" : "0x",
    "gasLimit" : "0x5208",
    "nonce" : "0x00",
    "to" : "0x0000000000000000000000000000000000000100",
    "value" : "0x01",
    "v" : "0x01",
    "r" : "0xa8f4757869fbb831ba4ed3a7c8f868b0e2e0c1eda97937aab035560fffdedf3c",
    "s" : "0x19d9b041540e3d6f5f56dc29deb8834a08171e92037cf567b922357e70f8e54a",
    "chainId" : "0x01",
    "type" : "0x03",
    "maxFeePerGas" : "0x07",
    "maxPriorityFeePerGas" : "0x00",
    "accessList" : [
    ],
    "maxFeePerBlobGas" : "0x01",
    "blobVersionedHashes" : [
        "0x0100000000000000000000000000000000000000000000000000000000000000"
    ]
}
```

the env provided 
```
"env" : {
            "currentBaseFee" : "0x07",
            "currentCoinbase" : "0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba",
            "currentDifficulty" : "0x00",
            "currentExcessBlobGas" : "0x240000",
            "currentGasLimit" : "0x016345785d8a0000",
            "currentNumber" : "0x01",
            "currentRandom" : "0x0000000000000000000000000000000000000000000000000000000000000000",
            "currentTimestamp" : "0x03e8"
        },
```

**Comment by marioevz** [comment]
If you apply the `get_blob_gasprice` function from the [EIP-4844](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4844.md#gas-accounting) to the `currentExcessBlobGas` value, you get `0x02` as the result, the transaction has `maxFeePerBlobGas==0x01` which is lower than the minimum value the current environment expects, therefore the transaction is invalid.

**Comment by spencer-tb** [comment]
Adding here as I wrote it out already :D 

From the EIP we have the following formula:
```python
def get_blob_gasprice(header: Header) -> int:
    return fake_exponential(
        MIN_BLOB_GASPRICE,
        header.excess_blob_gas,
        BLOB_GASPRICE_UPDATE_FRACTION
    )
 ```
 If we utilize `currentExcessBlobGas` from the `env`, we end up wil a positive value for `get_blob_gasprice`.  As Mario mentioned specifically `0x02`.
 
 For the tx to be valid, it must pass this check:
 ```python
 assert tx.max_fee_per_blob_gas >= get_blob_gasprice(block.header)
 ```
 As `"maxFeePerBlobGas" : "0x01"` < `0x02`, the tx is invalid, with the error: `INSUFFICIENT_MAX_FEE_PER_BLOB_GAS`
