### ISSUE TITLE
rlp_decoded vs provided rlp inconsistency

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#415]
have this issue:
```
Error: Error checking invalid block rlp.tx vs rlp_decoded tr `{
    "data" : "0x",
    "gasLimit" : "0x07a120",
    "nonce" : "0x00",
    "to" : "",
    "value" : "0x01",
    "v" : "0x01",
    "r" : "0x990fd9e8068282f2f657fda1fc17ba168b6ccb064a796796a04647268efdc0ba",
    "s" : "0x5497398a0d1bfe95930e450561b2a88ece16b0212a4784e92b0a7cd3921852c4",
    "chainId" : "0x01",
    "type" : "0x03",
    "maxFeePerGas" : "0x07",
    "maxPriorityFeePerGas" : "0x00",
    "accessList" : [
    ],
    "maxFeePerBlobGas" : "0x01",
    "blobVersionedHashes" : [
        "0x0100000000000000000000000000000000000000000000000000000000000000"
    ]
}` 
is different to rlp_decoded tr 
`{
    "data" : "0x",
    "gasLimit" : "0x07a120",
    "nonce" : "0x00",
    "to" : "0x0000000000000000000000000000000000000100",
    "value" : "0x01",
    "v" : "0x01",
    "r" : "0x8633745d9ccae895b1cd9b35473bf2c2f19230b32ebecf93fcf6e98e08868a7f",
    "s" : "0x2df5e81e127ad763e99e70e134ea214d74d47e80787950b1959551c7b61f68ea",
    "sender" : "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b",
    "chainId" : "0x01",
    "type" : "0x03",
    "maxFeePerGas" : "0x07",
    "maxPriorityFeePerGas" : "0x00",
    "accessList" : [
    ],
    "maxFeePerBlobGas" : "0x01",
    "blobVersionedHashes" : [
        "0x0100000000000000000000000000000000000000000000000000000000000000"
    ]
}`) (cancun/eip4844_blobs/tests/tmp/tmptest_f077683c_5413_4e48_a90e_1c767f88f5d6/test_blob_txs.py::test_invalid_blob_tx_contract_creation[fork_Cancun-blockchain_test-], fork: Cancun, block: 1)
```

the transaction that appars in rlp_decoded is different to the one that is actually passed in rlp field.

**Comment by winsvega** [comment]
actually I thought about rlp_decoded. 
the only case where it can;t be done is when rlp is invalid.  (and this ones are rlp serialization tests) 

but we can actually agree to print rlp_decoded to specificly indicate that the block has some field missing. 
so if blobGasUsed field is missing it will be like 
"blobGasUsed" : "not included in rlp"  or smth as a hint. 
and if there are extra fields it can print it too
"extraField1" : "..."

and then if we construct invalid block with >256 values we can also indicate it in rlp_decoded
so the user will see what is going on in this rlp.

**Comment by winsvega** [comment]
and this test should not produce any rlp_decoded or should note in it that the transaction rlp is invalid

Error: Unhandled UpwardsException: Failed to verify rlp vs rlp_decoded in filled block: BlobTransaction::fromRLP(RLP) expected to have exactly 14 elements! (cancun/eip4844_blobs/src/GeneralStateTestsFiller/Pyspecs/cancun/eip4844_blobs/test_blob_txs_full.py::test_reject_valid_full_blob_in_block_rlp[fork_Cancun-blockchain_test-one_full_blob_at_the_end_max_txs], fork: Cancun, block: 1)

**Comment by marioevz** [comment]
I think we could close this now that #427 is merged or is there anything left to be fixed @winsvega ?

**Comment by winsvega** [comment]
Yes.

**Comment by winsvega** [comment]
solved for now by not printing rlp_decoded for some cases
