### ISSUE TITLE
Refactor Blockchain/StateTests (ethereum_test_tools/spec) for clearer Environment Abstration

### ISSUE THREAD

**Issue by spencer-tb** [ethereum/execution-spec-tests#43]
From https://github.com/ethereum/execution-spec-tests/pull/37, via marioevz: 

> Looking at my code on make_block in BlockchainTests it seems like was really easy to make this mistake in the first place because of how the block and env are just mixed all over the place. I think it would be nice to refactor this a bit on a different PR to make a clear distinction that block structure is the source of the test information, but env is the structure that should contain all the correct information at some point.
> 
> I think this same mistake could be present in the StateTests, it's just that we don't have any withdrawals tests written in the StateTests format.

**Comment by danceratopz** [comment]
See #307.

**Comment by spencer-tb** [comment]
We are well overdue to closing this one :)
