### ISSUE TITLE
feauture request: make Op.OOG pseudo Opcode

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#455]
in the test we can use this parametrization:

```
@pytest.mark.parametrize("call_return", [Op.REVERT, Op.RETURN])
```

which easilty types with 

```
action=Op.MSTORE(0, Op.TLOAD(0)) + call_return(0, 32),
```

but then I need to check one more revert scenario is when the call goes OOG. 
would be nice to have just one more `Op.OOG`  that would  just put this bytes into code `Op.SHA3(0, Op.SUB(0, 1)) ` and ignore arguments

**Comment by marioevz** [comment]
Closing as PR was merged.
