### ISSUE TITLE
generate tests with Paris keyword instead of Merge

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#469]
lets follow the standard

Fixtures generated for Paris still use the network name "Merge" instead of "Paris". 

For example:
```
fill tests/istanbul/eip1344_chainid/test_chainid.py::test_chainid[fork_Paris-blockchain_test] --output fixtures/
```
generates a json file with the network name set to "Merge":
```
grep network fixtures/blockchain_tests/istanbul/eip1344_chainid/chainid/chainid.json 
# ->        "network": "Merge",
```

**Comment by raxhvl** [comment]
I believe this is related to #362 which is closed by #363. Could you tell me what else is required?

**Comment by danceratopz** [comment]
Thanks @raxhvl, yes, this was mainly solved by #363, at least internally in the code. I've updated the original issue with more explanation :+1:

**Comment by danceratopz** [comment]
@marioevz do we want to change this? Just wanted to double check.

@raxhvl it's a very quick one line change (L305):
https://github.com/ethereum/execution-spec-tests/blob/f8c435e295a0b1e4dcb544af1b9154cc052d4aa1/src/ethereum_test_forks/forks/forks.py#L302-L309

**Comment by raxhvl** [comment]
@danceratopz I did rename line `305` here #480. 
However, I tried intentionally misspelling "paris" to get the test to fail but it never did. So not very confident if this has the desired effect.

**Comment by spencer-tb** [comment]
@raxhvl - made a quick comment on the PR! I'm all for it, just requires maybe a bit of prodding client teams

I think it should be okay to have so long as we mention it being a breaking change on the next release

**Comment by raxhvl** [comment]
Got it. Do we have a place to keep track of this issue?
