### ISSUE TITLE
How do I get this working?

### ISSUE THREAD

**Issue by qbzzt** [ethereum/execution-spec-tests#49]
I followed the directions to install, and now when I try to run a test I get:

```
(venv) qbzzt1@spec-tests:~/execution-spec-tests$ tf --output="fixtures" --test-case dup
DEBUG:ethereum_test_filling_tool.main:searching example.example for fillers
DEBUG:ethereum_test_filling_tool.main:searching vm.chain_id for fillers
DEBUG:ethereum_test_filling_tool.main:searching vm.dup for fillers
DEBUG:ethereum_test_filling_tool.main:searching withdrawals.withdrawals for fillers
DEBUG:ethereum_test_filling_tool.main:searching eips.eip3651 for fillers
DEBUG:ethereum_test_filling_tool.main:searching eips.eip3855 for fillers
DEBUG:ethereum_test_filling_tool.main:searching eips.eip3860 for fillers
INFO:ethereum_test_filling_tool.main:collected 1 fillers
DEBUG:ethereum_test_filling_tool.main:filling dup
Exception during test ''
Traceback (most recent call last):
  File "/home/qbzzt1/execution-spec-tests/venv/bin/tf", line 8, in <module>
    sys.exit(main())
  File "/home/qbzzt1/execution-spec-tests/src/ethereum_test_filling_tool/main.py", line 180, in main
    filler.fill()
  File "/home/qbzzt1/execution-spec-tests/src/ethereum_test_filling_tool/main.py", line 140, in fill
    fixture = filler(t8n, b11r, "NoProof")
  File "/home/qbzzt1/execution-spec-tests/src/ethereum_test_tools/filling/decorators.py", line 67, in inner
    return fill_test(
  File "/home/qbzzt1/execution-spec-tests/src/ethereum_test_tools/filling/fill.py", line 55, in fill_test
    raise e
  File "/home/qbzzt1/execution-spec-tests/src/ethereum_test_tools/filling/fill.py", line 45, in fill_test
    (blocks, head, alloc) = test.make_blocks(
  File "/home/qbzzt1/execution-spec-tests/src/ethereum_test_tools/spec/state_test.py", line 111, in make_blocks
    (alloc, result, txs_rlp) = t8n.evaluate(
  File "/home/qbzzt1/execution-spec-tests/src/evm_transition_tool/__init__.py", line 209, in evaluate
    raise Exception("failed to evaluate: " + result.stderr.decode())
Exception: failed to evaluate: ERROR(3): EIP-1559 config but missing 'currentBaseFee' in env section
```

How do I add the proper field to the env? Better yet, how do I add it to the default environment?

**Comment by spencer-tb** [comment]
Apologies, we've wrote on the README.md that the required `go-ethereum` version should be `v1.10.13`, but currently to create all test fixtures (and run all test fillers) you will need to use the most up-to-date `go-ethereum` [master branch](v1.10.13).

**Comment by qbzzt** [comment]
This can't be it, because I'm using geth 1.10.26:

```
qbzzt1@spec-tests:~/execution-spec-tests$ evm --version
evm version 1.10.26-stable-e5eb32ac
qbzzt1@spec-tests:~/execution-spec-tests$ 
```

**Comment by spencer-tb** [comment]
That release doesn't work me as well, as I believe it was released last November. The most up-to date master branch works for me built from source :smile: 

```
evm version 1.11.0-unstable-55f41d19-20230126
```

Similarly, the branch used in our [release](https://github.com/ethereum/execution-spec-tests/releases/tag/v0.2.1) should work. Hope this helps, I'll make a change to the README.

**Comment by qbzzt** [comment]
I want to use the latest spec tests (I plan on adding to them, after all), so I'll just use the latest master. Any special things I need to do to compile geth?

**Comment by qbzzt** [comment]
Thank you, it works now. I assume that after I get it working I run, for example, `fixtures/vm/dup/dup.json` with `retesteth`?

**Comment by spencer-tb** [comment]
Great! Yeah that sounds correct.

_Although you have it working I am going to leave this here for future reference:_

Here is a fast way to build geth from source in order to get the most up to date `evm` binary:
```
git clone https://github.com/ethereum/go-ethereum.git && cd go-ethereum
make all
```

To add the built `evm` binary to PATH, the most flexible option is to create a symlink to the binary. I use linux so for me this is: 
```
ln -s build/bin/evm /usr/bin/evm
```
This allows you to change branches and re-build the `evm` binary on the fly.

**Comment by qbzzt** [comment]
Thank you.
