### ISSUE TITLE
Fixture Format: Add transactions/uncleHeaders/withdrawals for BlockchainTests

### ISSUE THREAD

**Issue by spencer-tb** [ethereum/execution-spec-tests#56]
Add the following fields for BlockchainTests. Omit the withdrawals field unless >= Shanghai fork. WIP: PR #47 

![image](https://user-images.githubusercontent.com/60348173/215601338-cf9343fc-9f22-4b3b-9d6e-e538572c4720.png)

**Comment by winsvega** [comment]
chainname is optional and deprecated. it was used for multichain blockchain tests where chain reorg happen due to  total difficulty. it is a debug field for user to read. not needed anymore as it is only one chain now.

**Comment by spencer-tb** [comment]
Closing after merging: #47
