### ISSUE TITLE
feat/refactor: extend `EthRPC` framework class and use it in `gentest.py`

### ISSUE THREAD

**Issue by danceratopz** [ethereum/execution-spec-tests#561]
#556 added classes to help calling ETH and Engine API methods on clients, we should extend these classes and refactor `gentest.py` to use them:
https://github.com/ethereum/execution-spec-tests/blob/aa1a57137084e4865651f6f780627c4a4e13a429/src/cli/gentest.py#L243-L254

**Comment by ThreeHrSleep** [comment]
I would like to give it a try :)

**Comment by murluki** [comment]
could you please assign this to me?
