### ISSUE TITLE
output fixtures have tests with the same names

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#75]
`withdrawals_use_value_in_contract.json`  has test vector     `"000_shanghai" : {`
`withdrawals_many_withdrawals.json` has test vector     `"000_shanghai" : {`

this will confuse when we try to speak about errors in `000_shanghai` test

**Comment by spencer-tb** [comment]
Thanks for this! We tried to address the latter in this PR as I was having issues debugging tests in hive for the same reason: #69 

I am open to adding the file name to the name within the fixture, as I assume if I am a client developer using the tests I will have only have `000/shanghai`. When running these tests in hive I preprocess the file name and append it to the head of the latter.

> The end result of the PR: #69 was that if the fixture_name in `<fixture_name>.json` was descriptive enough we did not need the name added within the test i.e. `000/shanghai`. We chose to keep it like this as we could simply use `fixture_name/000/shanghai` to determine the test (as the fixture_name correlates directly to the test_case name in a (python) module, i.e. `test_use_value_in_contract()` in `withdrawals.py`).
> 
> If however, we have multiple tests that are distinctly different within a fixture file (testing _slightly_ different things within a module), we would add a `tag` to the yielded test. For example in `multiple_withdrawals_same_address.json` we have 2 tests. 
> - The first test `000/shanghai` or using the test name `multiple_withdrawals_same_address/000/shanghai` tests that withdrawals can be done to the same address multiple times in the same block. 
> - The second test `001/multiple_blocks/shanghai` does the same thing but for multiple blocks hence has the `tag="multiple_blocks"`. With the fixture name this is: `multiple_withdrawals_same_address/001/multiple_blocks/shanghai`.

**Comment by winsvega** [comment]
I use the rule 
test name in file should be the same as filename itself so not to confuse.

**Comment by danceratopz** [comment]
Fixed after the pytest refactor.
