### ISSUE TITLE
🔀(gentest): use jinja2 templates to structure python output

### ISSUE THREAD

**Issue by danceratopz** [ethereum/execution-spec-tests#863]
[Jinja2](https://jinja.palletsprojects.com/en/3.1.x/) is a very powerful templating library that we started using in the doc flow for the generated "Test Case Reference" output pages, see #801 and `./docs/templates`.

I think that `.py.j2` templates could be an excellent way to write the output from `gentest`. This will be particularly helpful, when/if we create `blockchain_tests` with an arbitrary number of blocks, each containing an arbitrary number of transactions. We could have a template for a `state_test` and one for `blockchain_test`. Jinja2 also allows base templates.

**Comment by raxhvl** [comment]
Hey @danceratopz I'm starting with this.
