### ISSUE TITLE
🐞(gentest): generate test cases as a `state_test` for single transactions

### ISSUE THREAD

**Issue by danceratopz** [ethereum/execution-spec-tests#864]
Currently, `gentest` generates test cases in the `blockchain_test` format. 

However, if a test case can be expressed as a `state_test`, `state_test` is the preferred format. This is because:

- `fill` will additionally generate a `blockchain_test` fixture from `state-tests` (consisting of one block and one transaction). 
- The `state_test` format provides more targeted testing, as it does not invoke a client's block building machinery (for exception tests, this can lead to false positives, see #343).

Bonus points for adding this rationale to EEST's HTML documentation in "Writing Tests" :slightly_smiling_face:.

**Comment by raxhvl** [comment]
Picking this up next.
