### ISSUE TITLE
Documentation link should go to the stable release

### ISSUE THREAD

**Issue by chfast** [ethereum/execution-spec-tests#906]
Documentation link: https://ethereum.github.io/execution-spec-tests/ goes to the recent pre-release. This is quite confusing and it's not easy to switch to stable because there is a lot of options to choose from.

**Comment by danceratopz** [comment]
Done.

- Manually set the docs `latest` alias to `v3.0.0`:
    ```bash
    uv run mike alias --rebase --push -u v3.0.0 latest
    ```
- Cherry-picked the fix https://github.com/ethereum/execution-spec-tests/commit/802467c890e55cac89ad903585f01e440f701728 to `verkle/main` so a new verkle release won't overwrite the docs `latest` alias again.

**Comment by danceratopz** [comment]
jfyi @spencer-tb!

**Comment by danceratopz** [comment]
Got clobbered by a verkle pre-release again in the meantime. Verkle got released on the commit before the fix :sweat_smile: 

Fixed again.
