### ISSUE TITLE
Conflicting dependencies

### ISSUE THREAD

**Issue by yerke26** [ethereum/execution-spec-tests#953]
The conflict is caused by:
ethereum-execution-spec-tests 1.0.0 depends on pydantic<2.9 and >=2.8.0
ethereum-spec-evm-resolver 0.0.5 depends on pydantic<3 and >=2.9.2

**Comment by danceratopz** [comment]
Hi @yerke26 thanks for flagging this. Could it be that you're installing eest using `pip`? I.e., via `pip install -e` or similar? My internet is very flaky and I can't verify this at the mo.

If so, try using `uv` instead, the tool we use to maintain our package dependencies, see "Getting Started":
https://ethereum.github.io/execution-spec-tests/main/getting_started/installation/

Sorry if you got caught by out-dated docs in the v3.0.0 version of our docs, please make sure that you use the `main` version in the docs version pull-down selector in the top of the page - perhaps we should change that to the default.

Btw, I'm very happy to help you add `nethtest` support if that's your aim; just ping on Discord or Telegram! (please note, I'm traveling today).

**Comment by yerke26** [comment]
Hi @danceratopz, thanks for replying
I was building retesteth docker image and it uses pip. changed to uv and it works. Will open this issua on retesteth side to change it to uv
